### ISSUE TITLE
Some tile highlighting doesn't work

### ISSUE THREAD

**Issue by 6lancmange** [Ceddini/CoreKeeperMapTool#16]
As mentioned in a comment to a different issue, all boulders except copper don't appear. This also applies to Fungal Soil and _possibly_ Ancient Gemstone Ore (or I just don't have any currently discovered, but it's possible that I do and it doesn't show up). Also I thought Rug didn't work, but it seems it's only the default colour that shows up, and all the other painted versions just aren't implemented at all (pretty please?).

**Comment by Ceddini** [comment]
I'll reply here, since I closed the other one already.

Map is working for me. You sure your map has more boulders? Try the example map to make sure. That one (as can be seen in the picture) has other boulders ![Screenshot_2022-11-25-15-33-32-91_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/21086465/204006649-ff26211c-9973-4c90-9765-7ba7df03b97e.jpg)


Ancient Gemstone Ore seems to work as well:
![Screenshot_2022-11-25-15-37-12-61_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/21086465/204007059-eba13955-006a-4b86-a18f-54edecb6b727.jpg)
You can also verify it in the example map.

Fungal soil might not be in the example map, since it was added in a later patch I think. So I'll have to check it out later.


And yeah, wanted to add all the tiles (that inlcudes the colored carpets) but I didn't get around to it yet, since I wasn't on the PC where I have the formatted list in over a week. I'll definitely do it tomorrow though 😬

**Comment by 6lancmange** [comment]
Welp, it seems maybe I don't have any other boulders, actually? I don't know, I found a gold one and took a screenshot while standing next to it to be sure where it was, and that one shows up on the map tool. Weird, I was sure I've seen some others while running around. I'll have to check once I see one again.

As for the Fungal Soil:
![obraz](https://user-images.githubusercontent.com/26997029/204060678-880f7ab9-29f9-4854-bb96-5f0b6d4e3eb4.png)
as you can see, there are two bands of it in the right farm, not highlighted. I see you included Stone Moss, are any others also planned?

**Comment by Ceddini** [comment]
Huh. I might have messed up the RGB values by accident. Will check it out today. 

I have the color values of all the things that show up in the minimap, so I should be able to add everything

**Comment by Ceddini** [comment]
Sorry for the delay! Had family visiting, so I had to take some time away from my pc.

Should be fixed now. Turns out the color picker I used had a +1 for the blue value (61 instead of 60).
