### ISSUE TITLE
"Show biomes" doesn't work unless manual rotation is toggled on?

### ISSUE THREAD

**Issue by 6lancmange** [Ceddini/CoreKeeperMapTool#17]
As said in the title, I expected to see something happen when toggling the "show biomes" button, but nothing happens. Unless you also toggle manual rotation.

Also, in this and probably all other instances, "transparency" is used where it should be "opacity", since the effect becomes LESS transparent as you move the slider to the right, increasing value. Or invert the slider, I suppose.

**Comment by Ceddini** [comment]
If it's a bug or not depends on your map. If there's not enough data available to really know where the borders are, I decided to just not show it instead of completely wrong. That was kinda before the manual rotation existed, so I just might remove that "safety".

Dev Version already has a note about manual rotation being needed for the biomes if they're wrong.


Opacity is definitely better in that circumstance, so I'll remove it asap in the dev version (probably tomorrow). Kinda fits into me translating everything

**Comment by 6lancmange** [comment]
I see either you've edited it or I explored some more, 'cause it works now. You mention the dev version a lot, is it available for everyone?

**Comment by Ceddini** [comment]
Didn't change anything, so you probably explored some more :)

And yes, dev Version is publicly available at https://maptool-dev.ceschmitt.de/
