### ISSUE TITLE
JSON fails to parse on bigger maps

### ISSUE THREAD

**Issue by rykdesjardins** [Ceddini/CoreKeeperMapTool#30]
There might be an issue when map files are too heavy. 

From console : `Uncaught SyntaxError: JSON.parse: expected ',' or ']' after array element at line 1 column 6940809 of the JSON data`

I believe since the browser is the one parsing the serialized data, there's a hard limit depending on the browser's configuration. Don't quote me on this, but I believe the default limit for parsing JSON is `2097152` characters, or 4MB or serialized unicode data. In the case of my `mapparts` file, once uncompressed weighs as much as 7.9MB. 

There might be a way around it if we'd parse the JSON data as a stream instead of as a chunk of data. ~This would make the process async, but would allow way bigger JSON objects to be parsed.~ 
Since the process is already async, this wouldn't change the flow and would allow huge JSON objects to be parsed locally.

There already exists solutions for this. For instance : 
- https://github.com/xtao-org/jsonhilo
- https://github.com/jimhigson/oboe.js/

If you're open to contributions, I would be happy to contribute this change, and add an error message as well when parsing fails. 

https://github.com/Ceddini/CoreKeeperMapTool/blob/dev/src/js/maploader.js#L32

**Comment by Ceddini** [comment]
Sorry for the late reply. I'm open for contributions, but currently just busy with my thesis.

Pretty sure that even if larger json data can get parsed, the browser still won't be able to actually render it, since it generates one of the two canvases in the full size of the image. And that canvas will probably end up being a few million pixels wide and/or high with a map that large. 
Not sure how the browser would handle a canvas that large... If it's smart it would only render the visible area, but I bet since it's the canvas that's super large, and not just the contents, it would try to render _everything_ at once.

if that's not an issue tho, i'd be more than happy to allow larger file sizes :)

**Comment by rykdesjardins** [comment]
@Ceddini Don't worry about it! This is an amazing open source contribution. Nobody should expect you to work on this full-time :slightly_smiling_face: 

The map file grew bigger since. Trying to `JSON.parse` it from the NodeJS shell also throws, but using a stream-based parser will somehow allow it to be read. Maybe this is in vain if it would be almost impossible to render the whole thing anyways. That is a lot of pixels and would likely crash the browser on smaller machines ; only rendering visible portions and doing manual compression on zoom-out seems to be the way to go, but that is a pretty substantial addition.

Could look into drafting something regarding only rendering the visible area. I've done something similar in the past and it boils down to computing a viewport and manually keeping track of the "camera" position before rendering chunks into fixed-size squares where needed. 

Curious to hear your thoughts!

Are you going to publish your thesis? This is exciting.

**Comment by Ceddini** [comment]
> That is a lot of pixels and would likely crash the browser on smaller machines ; only rendering visible portions and doing manual compression on zoom-out seems to be the way to go, but that is a pretty substantial addition.
>
> Could look into drafting something regarding only rendering the visible area. I've done something similar in the past and it boils down to computing a viewport and manually keeping track of the "camera" position before rendering chunks into fixed-size squares where needed.

Yeah, that's basically what I was thinking. I'd think the canvas rendering wouldn't render stuff if it's outside the viewport though (if the canvas is limited to the viewport size), so panning the content of the canvas might even be enough. Didn't want to do that though, since the screenshot feature wouldn't really work that well anymore. Or it would require stitching the image manually, which I really don't want to do. 

Another thing I was kinda thinking is if the whole map tool is even worth it for people who have a map large enough to stop the tool from working. Sure, tile highlighting is pretty nice, but if someone has explored hundreds of thousands of tiles, they probably don't really need to know where a tin boulder is. So not sure if spending a lot of time on adding a different renderingn solution and streaming the file is worth it in the end

> Are you going to publish your thesis? This is exciting.

I can't :) It contains info from my workplace, so would have to black out basically the second half and parts of the first 😅

**Comment by rykdesjardins** [comment]
> Sure, tile highlighting is pretty nice, but if someone has explored hundreds of thousands of tiles, they probably don't really need to know where a tin boulder is. So not sure if spending a lot of time on adding a different renderingn solution and streaming the file is worth it in the end

Yeah, that makes a lot of sens. Past a certain distance, the map tool won't offer much more info than the in-game map. The effort won't really add any real value. 

Bah! I'll close this issue~ I seem to be the only one experiencing it, too. Maybe my actual map files are weird, and the streaming parser silently ignores the errors. 

> I can't :) It contains info from my workplace, so would have to black out basically the second half and parts of the first sweat_smile

That's too bad! Wish you the best @Ceddini . Thanks for your open source contribution! Best of luck~
